# Part One: We tell him to run one version of our application (to avoid Node limits)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanobanana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanobanana
  template:
    metadata:
      labels:
        app: nanobanana
    spec:
      containers:
      - name: app-container
        # jenkins will edit this line in the new version
        image: musstapha1/nanobanana-app:v1.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-service" # service name inside the kubernetes
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "postgres"

---
# Part Two: We say we created a portal (Load Balancer) to access the Internet
apiVersion: v1
kind: Service
metadata:
  name: nanobanana-service
spec:
  type: LoadBalancer
  selector:
    app: nanobanana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
