# Part One: We tell him to run two versions of our application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanobanana-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nanobanana
  template:
    metadata:
      labels:
        app: nanobanana
    spec:
      containers:
      - name: app-container
        #هWe will put the name of the carton we just uploaded
        image: musstapha1/nanobanana-app:v1.0
        ports:
        - containerPort: 5000

---
# Part Two: We say we created a portal (Load Balancer) to access the Internet
apiVersion: v1
kind: Service
metadata:
  name: nanobanana-service
spec:
  type: LoadBalancer
  selector:
    app: nanobanana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
