apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:15        # Offical DockerHub Image
        ports:
        - containerPort: 5432
        env:                     # connecttion setup
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "nanobanana_db"

---
apiVersion: v1
kind: Service
metadata:
  name: db                      # reaching the db via Name of db
spec:
  type: ClusterIP               # Only Internal Connection 
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
