name: My First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run a simple test
        run: |
          echo "Hello Mustapha!"
          echo "The GitHub Actions Robot is successfully monitoring your code from the home PC! 🤖"
          echo "Automated Testing: PASSED ✅"
