name: Telegram Notification Pipeline

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Alert
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 تحديث جديد يا هندسة!
            تم تشغيل الـ Pipeline بنجاح.
            📦 المشروع: ${{ github.repository }}
            👤 بواسطة: ${{ github.actor }}
